pipeline {
    agent any
     environment {
        GOOGLE_PROJECT_ID = "vinaydevops" 
        credentials = file("sc_jenkins_terraform.json")
    }
    
    tools {
        terraform 'jenkins-terraform'
    }
    stages {
      
        stage ("terraform init") {
            steps {
                sh 'cd terraform && terraform init'
            }
        }
        stage ("terraform fmt") {
            steps {
                sh 'cd terraform && terraform fmt'
            }
        }
        stage ("terraform validate") {
            steps {
                sh 'cd terraform && terraform validate'
            }
        }
        stage ("terrafrom plan") {
            steps {
                sh 'cd terraform && terraform plan'
            }
        }
        stage ("terraform apply") {
            steps {
                sh 'cd terraform && terraform apply --auto-approve'
            }
        }
    }
}
